---
title: "Code Book"
author: "Scheitelhecht"
date: "29 April 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This Code Book describes all attributes of the resulting data file `tidy-data.txt`


## Identifiers


* `subject_ID`  (factor) : the ID of the test subject (person who performed differend activities), 30 persons took part
* `activity_name`(factor) : the type of activity performed (walking, sitting, ...) when the  measurement was taken

## Activity names

The test persons performed six different activities duringt the measurements.
Therefore the factor `activity_name` has the six items:

* `WALKING `
* `WALKING_UPSTAIRS `
* `WALKING_DOWNSTAIRS `
* `SITTING `
* `STANDING`
* `LAYING`

## Measurements

These are 86 measurement variables.  These are calculated mean values from the source data sets (please see the original <a href='UCI HAR Dataset/README.txt'>README.txt</a> )
). 

Measurements are normalized and bounded within [-1,1].

*	`	tBodyAcc-mean-X	`
*	`	tBodyAcc-mean-Y	`
*	`	tBodyAcc-mean-Z	`
*	`	tBodyAcc-std-X	`
*	`	tBodyAcc-std-Y	`
*	`	tBodyAcc-std-Z	`
*	`	tGravityAcc-mean-X	`
*	`	tGravityAcc-mean-Y	`
*	`	tGravityAcc-mean-Z	`
*	`	tGravityAcc-std-X	`
*	`	tGravityAcc-std-Y	`
*	`	tGravityAcc-std-Z	`
*	`	tBodyAccJerk-mean-X	`
*	`	tBodyAccJerk-mean-Y	`
*	`	tBodyAccJerk-mean-Z	`
*	`	tBodyAccJerk-std-X	`
*	`	tBodyAccJerk-std-Y	`
*	`	tBodyAccJerk-std-Z	`
*	`	tBodyGyro-mean-X	`
*	`	tBodyGyro-mean-Y	`
*	`	tBodyGyro-mean-Z	`
*	`	tBodyGyro-std-X	`
*	`	tBodyGyro-std-Y	`
*	`	tBodyGyro-std-Z	`
*	`	tBodyGyroJerk-mean-X	`
*	`	tBodyGyroJerk-mean-Y	`
*	`	tBodyGyroJerk-mean-Z	`
*	`	tBodyGyroJerk-std-X	`
*	`	tBodyGyroJerk-std-Y	`
*	`	tBodyGyroJerk-std-Z	`
*	`	tBodyAccMag-mean	`
*	`	tBodyAccMag-std	`
*	`	tGravityAccMag-mean	`
*	`	tGravityAccMag-std	`
*	`	tBodyAccJerkMag-mean	`
*	`	tBodyAccJerkMag-std	`
*	`	tBodyGyroMag-mean	`
*	`	tBodyGyroMag-std	`
*	`	tBodyGyroJerkMag-mean	`
*	`	tBodyGyroJerkMag-std	`
*	`	fBodyAcc-mean-X	`
*	`	fBodyAcc-mean-Y	`
*	`	fBodyAcc-mean-Z	`
*	`	fBodyAcc-std-X	`
*	`	fBodyAcc-std-Y	`
*	`	fBodyAcc-std-Z	`
*	`	fBodyAcc-meanFreq-X	`
*	`	fBodyAcc-meanFreq-Y	`
*	`	fBodyAcc-meanFreq-Z	`
*	`	fBodyAccJerk-mean-X	`
*	`	fBodyAccJerk-mean-Y	`
*	`	fBodyAccJerk-mean-Z	`
*	`	fBodyAccJerk-std-X	`
*	`	fBodyAccJerk-std-Y	`
*	`	fBodyAccJerk-std-Z	`
*	`	fBodyAccJerk-meanFreq-X	`
*	`	fBodyAccJerk-meanFreq-Y	`
*	`	fBodyAccJerk-meanFreq-Z	`
*	`	fBodyGyro-mean-X	`
*	`	fBodyGyro-mean-Y	`
*	`	fBodyGyro-mean-Z	`
*	`	fBodyGyro-std-X	`
*	`	fBodyGyro-std-Y	`
*	`	fBodyGyro-std-Z	`
*	`	fBodyGyro-meanFreq-X	`
*	`	fBodyGyro-meanFreq-Y	`
*	`	fBodyGyro-meanFreq-Z	`
*	`	fBodyAccMag-mean	`
*	`	fBodyAccMag-std	`
*	`	fBodyAccMag-meanFreq	`
*	`	fBodyBodyAccJerkMag-mean	`
*	`	fBodyBodyAccJerkMag-std	`
*	`	fBodyBodyAccJerkMag-meanFreq	`
*	`	fBodyBodyGyroMag-mean	`
*	`	fBodyBodyGyroMag-std	`
*	`	fBodyBodyGyroMag-meanFreq	`
*	`	fBodyBodyGyroJerkMag-mean	`
*	`	fBodyBodyGyroJerkMag-std	`
*	`	fBodyBodyGyroJerkMag-meanFreq	`
*	`	angle(tBodyAccMean,gravity)	`
*	`	angle(tBodyAccJerkMean),gravityMean)	`
*	`	angle(tBodyGyroMean,gravityMean)	`
*	`	angle(tBodyGyroJerkMean,gravityMean)	`
*	`	angle(X,gravityMean)	`
*	`	angle(Y,gravityMean)	`
*	`	angle(Z,gravityMean)	`

