---
title: "Readme"
author: "Scheitelhecht"
date: "29 April 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

"The README that explains the analysis files is clear and understandable." [Requirement from Course Project](https://www.coursera.org/learn/data-cleaning/peer/FIZtT/getting-and-cleaning-data-course-project)
 
## Getting the Input files

"The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:"

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


## Names of the Input files

 | path and name of input files | descrtiption  |
| ----------------------------------| -----------------------------------------------------------|
| /UCI HAR Dataset/`features.txt`| names of  561 features. "features" are the names of all measures taken from the mobile phone during the experiment (e.g.  accellerations in X, Y or Z direction). |
| /UCI HAR Dataset/`activity_labels.txt` | names of the six performed activities (walking, sitting, ...) |
| /UCI HAR Dataset/train/ `X_train.txt`| 7352 observations of the 561 feature variables |
| /UCI HAR Dataset/train/`y_train.txt` | a vector of 7352 activity IDs related  to the observations in `X_train.txt` |
| /UCI HAR Dataset/train/`subject_train.txt` |  a vector of 7352 subject IDs (persons) related to the measurements in `X_train.txt` |
| /UCI HAR Dataset/test/`X_test.txt`| 2947 observations of the 561 features
| /UCI HAR Dataset/test/`y_test.txt` | a vector of 2947 activity IDs related  to the observations in `X_test.txt`
| /UCI HAR Dataset/test/`subject_test.txt` | a vector of 2947 subject IDs (persons) related to the measurements in `y_train.txt`|


Note: This transformation  was performed using only the files above. The data files in the "Inertial Signals" folders were ignored.

## Name of the Output file

The name of the output file is `tidy-data.txt`.

It was generated by the script [run_analysis.R](run_analysis.R)

A detailed description of all variable can be found in the Code Book (`CodeBook.Rmd`)


##  Processing

* Download files from internet to a local folder
* unzip data files
* read all input data into data frames
* create meaningful column names
* merge the data frames
* extract only the measurements on the mean and standard deviation for each measurement
* convert `subject_ID` and  `activity_name` from numeric to factor
* create a  tidy data set with the average of each variable for each activity and each subject
* write the tidy data set into a csv file
 